language: node_js
node_js:
  - 12.4.0
os:
  - windows
  - linux
  - osx
before_install:
  - node -v
  - npm -v
  - npm install -g node-gyp
  - node-gyp -v
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm config set node_gyp "`npm prefix -g`\\node_modules\\node-gyp\\bin\\node-gyp.js"; else npm config set node_gyp "`npm prefix -g`/lib/node_modules/node-gyp/bin/node-gyp.js"; fi
  - npm config ls
install:
  - npm install
script:
  - npm test
# branches:
#   only:
#     - master
before_deploy:
  - npm run before-deploy
deploy:
  - provider: releases
    api_key:
      secure: rUlf9/bUEdvgKImX2ICiadVJPIbgSeVhxmxlBTE3cSbib5CvU/ADrVcIQrMyez5vuB3d7YYykClLofaIx2eTtb0JXJeHEk1hjbPVd0V4LihGKioxibSc0W2iidrDPsEw+s6s3etognb/1dmC0c2AzhE1G0zi2mLfRTG+sTvHhqAVHkc4gAz/J8zpA3sHPDquhK8a/XQ1ZbLAX4vP5IQ/8WW2hdCWfpKYfdIJDf1u7mmvT4BUfzdbjQXyP9wzny3SE/4KNoz+swUKxLfPnGbb/6COUI56BYI5bV9wQfk5wbIfpUkvGAKRMHIjeS9ne88V1szdamr965vWdTn0d5iCMQiVqZBkxwfV7scft3O6u99UA9KD/4oV1a+cYHa9mK+Ls/as34Q7bLL0Hu0fhgqkFj02LjUf0bvkRb5LFoSYd1MR5pKYvwXMFfcvYMq27F/gnumsKomEkbcGuvaCz1ST5yp2xqJLYMX9YwJQwaPvabsxzoGx1MMEqr44Au7NPlpQpa25mUql1O5Cw34kbe9YIWJN6hutqxgj2BnCPno1elLizBlm+H3r0pw9ngTchMxnxG/j/F3cOGJxvDsg7aiK89H7LFZHfhhOT/zt30829NtjZfvpReGSnP/5clHlJCFnRVo6RUhod+/R6hOVVlFl2mUHqDbRNUgOrm8a/MnNTKs=
    file: release/*.node
    file_glob: true
    skip_cleanup: true
    draft: true
    on:
      repo: toyobayashi/node-hca-decoder
      tags: true
  - provider: npm
    email: lifenglin314@outlook.com
    api_key:
      secure: q0ozRPePVQQnvlEl3VIowQ8V+S2bjoXLkzOAG6711l00B3hWyKhaQbuDlr0B252cULlAtFE0CY4jF0xbZMZJNPq4rURtEhwKtgInDvc1GlGPv/k03d2yS+GpCexBGWfHGi8wU5Dpbuq+EqYW2znFThFFGg7yFxUvIPyKFVEeNVI59YPr0JGxIHHtLRibOHaSBP5Ob0pds+owDUOwu8DnUixdB1yFUcynMl+WjWjxmrUdSZrqOCl1tT8RzedCxAAc34rev3I4yK03UkpnOh/HZqh/2cYldUF7HXiiX7Zj24/lqvlo/9XN/2SAyJs9IEGo7y7URTOIujI0vU8TrdXXnPBnFb+CKfaj3MZa5xeJ/LpAzMzYeYGxP3Pekxq6f0weYTve5Lv5bdAgZ8iyCcAT+j8qTPmANywJsfbB7sDDXXqpidEgC33ivajcBNQj9LusRoT523sDObC2RuNRQkg8uRcAt8XbZehd4MjufkPrfpKBB7+XkrgdJSE/Dl+kfrBWjT/IAgdHRxtTiATYvoeEw+n5TIjop7IXxd50JKW2BUQMLG1SXW2w9ZodAtkmLFUdUG2tAvCV8fY1ntgIY2rfWBGX37ukYyBsoYwyj1yfiqAUOvg6LA/obVLldZdl5/l63AuYevFAUvNm7XbLC4u2vwGXmWH861CF5Tarl4MYudQ=
    skip_cleanup: true
    on:
      tags: true
      repo: toyobayashi/node-hca-decoder
      condition: $TRAVIS_OS_NAME = linux
