language: node_js
node_js:
  - 12.4.0
os:
  - windows
  - linux
  - osx
before_install:
  - node -v
  - npm -v
  - npm install -g node-gyp
  - node-gyp -v
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then npm config set node_gyp "`npm prefix -g`\\node_modules\\node-gyp\\bin\\node-gyp.js"; else npm config set node_gyp "`npm prefix -g`/lib/node_modules/node-gyp/bin/node-gyp.js"; fi
  - npm config ls
install:
  - npm install
script:
  - npm test
# branches:
#   only:
#     - master
before_deploy:
  - npm run before-deploy
deploy:
  - provider: releases
    api_key:
      secure: TIT03m3GAXLLf29vb8b7kViZEhcrM8B0RQG1HpBu9GHD0a594cCLovgSvpCJojWmy74QzX5EYqX+rFNuS6Xrrh9EGCGb3lVLsq9fUMPkY8z4eXUD05RG+CBMOF1KECi3fqzkWD/bDfKc0WxZGyHr/i8M9s0xSlhNpl+QWKkiGBqD1/renZ4aMnm0PCPL1G18jhhGTJk+mKMOWMH01vyIXc8qwfDnG8zC8Mq3ynJ1coyIbAoVcZJOX9TMqUYL5ty3ERI39N1dpzXkx8MVCiDbLinPghDXEROF3qRqVQZhl1QYVx/2C5H7QE9QAjPOO+y7K9vG3udIIkP+jTZhGWXKOurqAmf7KNoyPRwxuMiUL2VkIlTJTYg1vvUFKszyONGgTDubmqZqsJy8iwdd4b6R73bDZtZgRQs3biX0gVUu+StL2JR8sOWabEGPUWJsheKJAbREz+tKncRcUyRY+S5T5G3vUWWs5M/zTXplg5SqKI3E/acRNpBt/nl5MiY+vWVJsm7QWPRZ72wczeam4tL+4q3lyrg59OugQedbfBY6bCCt9gt/J6+97gtPeuRXppcjdV7JXTvUgkfn/s7+3/oPZns7QNhl8hMTC5KLD6aVC+ov5VubIB9ygfZp0g5g6BLAkdKMdOz7/rIhK6Dfxqit6ULkOIfpIDwCIkeRKFFamfc=
    file: release/*.node
    file_glob: true
    skip_cleanup: true
    draft: true
    on:
      repo: toyobayashi/node-hca-decoder
      tags: true
  - provider: npm
    email: lifenglin314@outlook.com
    api_key:
      secure: ezd2/VjUf3W++NUfIIEsE3BM0+4UpWGG+avjnCHb7hisLS44K65ibtaUR1uC3M6xdxSxccF7HLSLmEFvguyXOHHFsueEW8MYh+qghtGfCBHJKsdAWp+eocQ/epblGiiKfvu6a9GfNPEW8XDN9MIFci9j2IPU7rcUP6vraG8nZPgKBgweXjvmhdLaE2q777RjXYMG7kMPhunNTTimH816tTavy4UUUzQlRUeV84YuNOTSyF4Dihy4d+zDWXe8VnRYK3WGuqaU7OqVxVilbZnurXN+lRNlMZNsfZEV2Z3/ELCBwZ0LeuL1ihAZmwTK8MglYr7qraBfkU1Bh4TM0p0mO67tYwDB2xeNYpD7oHwaEoa86YfxqFXHbH59z+Jcp2XkDOtDkYlHNt/XQ2SmER5wpg6gIRoJnjBW6v4XknN5u211ZhVcM6+sb7VvuzyAoOBUZoduLEzy7RxzIKEUy6bM+zOjOqUuA15el6DmeaSGTPxlSigj1dB0KAGbgfx7ZHr43ri7miOePoG6Zmwbt0Bd9xcMO7o++FQkfJVmksXDiX4fOTrDucy7k5tE71HgfmABlTIA958LEYSAQbMafF5RvJocQhBdfIDyad0/DSyKBlKGweD6zenQtGieWaCnG5GW5UstJwT5cHc0CrDTJ+N8z9j1Qu19k8Z0D0M/9DsWU4g=
    skip_cleanup: true
    on:
      tags: true
      repo: toyobayashi/node-hca-decoder
      condition: $TRAVIS_OS_NAME = linux
